name: chinese_words
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_redux: ^0.5.3
  json_serializable: ^2.0.2
  redux_epics: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.2.8

flutter:
  uses-material-design: true
  assets:
    - assets/output.json
